//Alert
export const ALERT_REMOVED = "ALERT_REMOVED";
export const ALERT_SETTED = "ALERT_SETTED";

//MixValues
export const LOADINGSPINNER_UPDATED = "LOADINGSPINNER_UPDATED";

//Auth
export const USERAUTH_LOADED = "USERAUTH_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const EMAILAUTH_SENT = "EMAILAUTH_SENT";
export const EMAIL_ERROR = "EMAIL_ERROR";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const REMOVEAUTH_ERROR = "REMOVEAUTH_ERROR";

//Users
export const USER_LOADED = "USER_LOADED";
export const USERS_LOADED = "USERS_LOADED";
export const USERSSECONDARY_LOADED = "USERSSECONDARY_LOADED";
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_UPDATED = "USER_UPDATED";
export const USER_DELETED = "USER_DELETED";
export const USERS_CLEARED = "USERS_CLEARED";
export const USERS_ERROR = "USERS_ERROR";
export const USERSSECONDARY_ERROR = "USERSSECONDARY_ERROR";
export const REMOVEUSER_ERROR = "REMOVEUSER_ERROR";

//Vessels
export const VESSEL_LOADED = "VESSEL_LOADED";
export const VESSELS_LOADED = "VESSELS_LOADED";
export const VESSEL_REGISTERED = "VESSEL_REGISTERED";
export const VESSEL_UPDATED = "VESSEL_UPDATED";
export const VESSEL_DELETED = "VESSEL_DELETED";
export const VESSELS_CLEARED = "VESSELS_CLEARED";
export const VESSEL_CLEARED = "VESSEL_CLEARED";
export const VESSELS_ERROR = "VESSELS_ERROR";
export const VESSEL_ERROR = "VESSEL_ERROR";
export const REMOVEVESSEL_ERROR = "REMOVEVESSEL_ERROR";

//Reservations
export const RESERVATION_LOADED = "RESERVATION_LOADED";
export const RESERVATIONS_LOADED = "RESERVATIONS_LOADED";
export const RESERVATION_REGISTERED = "RESERVATION_REGISTERED";
export const RESERVATION_UPDATED = "RESERVATION_UPDATED";
export const RESERVATION_DELETED = "RESERVATION_DELETED";
export const UNPAIDRESERVATIONS_DELETED = "UNPAIDRESERVATIONS_DELETED";
export const RESERVATIONS_CLEARED = "RESERVATIONS_CLEARED";
export const RESERVATION_CLEARED = "RESERVATION_CLEARED";
export const RESERVATIONS_ERROR = "RESERVATIONS_ERROR";
export const REMOVERESERVATION_ERROR = "REMOVERESERVATION_ERROR";

//Days
export const MONTHAVAILABILITY_LOADED = "MONTHAVAILABILITY_LOADED";
export const DAYAVAILABILITY_LOADED = "DAYAVAILABILITY_LOADED";
export const DAY_DISABLED = "DAY_DISABLED";
export const DAY_ENABLED = "DAY_ENABLED";
export const DAYSAVAILABILITY_CLEARED = "DAYSAVAILABILITY_CLEARED";
export const DAYSAVAILABILITY_ERROR = "DAYSAVAILABILITY_ERROR";

//Payment
export const PAYMENT_REGISTERED = "PAYMENT_REGISTERED";
export const PAYMENT_CANCELED = "PAYMENT_CANCELED";
export const PAYMENT_ERROR = "PAYMENT_ERROR";

//Discrepancy
export const DISCREPANCIES_LOADED = "DISCREPANCIES_LOADED";
export const DISCREPANCIES_UPDATED = "DISCREPANCIES_UPDATED";
export const DISCREPANCY_DELETED = "DISCREPANCY_DELETED";
export const DISCREPANCIES_CLEARED = "DISCREPANCIES_CLEARED";
export const DISCREPANCIES_ERROR = "DISCREPANCIES_ERROR";
export const REMOVEDISCREPANCY_ERROR = "REMOVEDISCREPANCY_ERROR";
